export enum SimplexErrorCodes{
    NOT_OPERABLE_OPERANDS = "NOT-OPERABLE-OPERANDS",
    INDEX_OUT_OF_RANGE = "INDEX-OUT-OF-RANGE",
    NEW_ROW_WITH_DIFFERENT_LENGTH = "NEW-ROW-WITH-DIFFERENT-LENGTH",
    INDEX_NOT_FOUND = "INDEX-NOT-FOUND",
    COMPONENT_NOT_FOUND_IN_BOARD = "COMPONENT-NOT-FOUND-IN-BOARD"
}