import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import ProviderStore from "@/store/Provider";
import SideBar from "@/components/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Optimizer IO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="./images/svg/Logo.svg"
          type="image/x-icon"
        />
      </head>
      <body className={`${inter.className} min-h-[100dvh]`}>
        <ProviderStore>
          <Header />
          <div className="flex relative">
            <SideBar />
            <main className="-border-2 border-green-400 flex-1">
              {children}
            </main>
          </div>
        </ProviderStore>
        <footer></footer>
      </body>
    </html>
  );
}
